### ISSUE TITLE
You should mention VSCodium instead of Visual Studio Code

### ISSUE THREAD

**Issue by Openstreetmapler** [WitheredKnights/resourcePack-Tutorial#1]
https://github.com/WitheredKnights/resourcePack-Tutorial/blob/1c8557baadb45792f97eda8971a990af94812f03/README.md?plain=1#L130

[_Visual Studio Code_](https://code.visualstudio.com/) is actually not open-source because **it contains proprietary code by Microsoft!** Also, it tracks the user by sending telemetry data. 

[_VSCodium_](https://vscodium.com/), which only contains the code from the [_vscode_ repository](https://github.com/microsoft/vscode), is **truly open-source** and doesn’t track the user by default.

I suggest you to add a link for _VSCodium_ to README.md and maybe remove the _Visual Studio Code_ link.

**Comment by PrimeTDMomega** [comment]
done!
p.s. - this repository isn't really maintained since we've moved our focus to other projects but thx for looking out still !
